//
//  DBWSettingsTableViewController.m
//  Workout
//
//  Created by Ben Rosen on 8/3/17.
//  Copyright © 2017 Ben Rosen. All rights reserved.
//

#import "DBWSettingsTableViewController.h"
#import <VTAcknowledgementsViewController/VTAcknowledgementsViewController.h>
#import <VTAcknowledgementsViewController/VTAcknowledgement.h>
#import "DBWAboutTableViewController.h"
#import "DBWCustomizeWorkoutPlanViewController.h"

@interface DBWSettingsTableViewController ()

@end

@implementation DBWSettingsTableViewController

- (instancetype)init {
    return [super initWithStyle:UITableViewStyleGrouped];
}

- (void)viewDidLoad {
    [super viewDidLoad];
}

- (void)didReceiveMemoryWarning {
    [super didReceiveMemoryWarning];
    // Dispose of any resources that can be recreated.
}

#pragma mark - Table view data source

- (NSInteger)numberOfSectionsInTableView:(UITableView *)tableView {
    return 2;
}

- (NSInteger)tableView:(UITableView *)tableView numberOfRowsInSection:(NSInteger)section {
    return section == 0 ? 2 : 1;
}

- (UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath {
    UITableViewCell *cell = [tableView dequeueReusableCellWithIdentifier:@"acknowledgement-identifier"];
    if (!cell) {
        cell = [[UITableViewCell alloc] initWithStyle:UITableViewCellStyleValue1 reuseIdentifier:@"acknowledgement-identifier"];
    }
    
    if (indexPath.section == 0) {
        cell.textLabel.text = indexPath.row == 0 ? @"About" : @"Acknowledgements";
    } else if (indexPath.section == 1) {
        cell.textLabel.text = @"Customize workout plan";
    }
    
    cell.accessoryType = UITableViewCellAccessoryDisclosureIndicator;
    
    
    return cell;
}

- (NSString *)tableView:(UITableView *)tableView titleForHeaderInSection:(NSInteger)section {
    return section == 0 ? @"About" : @"Workout";
}

- (void)tableView:(UITableView *)tableView didSelectRowAtIndexPath:(NSIndexPath *)indexPath {
    [tableView deselectRowAtIndexPath:indexPath animated:YES];
    
    if (indexPath.section == 0) {
        if (indexPath.row == 0) {
            DBWAboutTableViewController *aboutVC = [[DBWAboutTableViewController alloc] init];
            [self.navigationController pushViewController:aboutVC animated:YES];
        } else  if (indexPath.row == 1) {
            // automatically the acknowledgements cell
            NSString *path = [[NSBundle mainBundle] pathForResource:@"Acknowledgements" ofType:@"plist"];
            VTAcknowledgementsViewController *acknowledgementsVC = [[VTAcknowledgementsViewController alloc] initWithPath:path];
            acknowledgementsVC.headerText = @"I used the following libraries to help make development of the app easier and more prosperous.";
            acknowledgementsVC.footerText = @"Generated by Cocoapods and icons from The Noun Project";
            
            VTAcknowledgement *customLicense = [[VTAcknowledgement alloc] initWithTitle:@"The Noun Project" text:@"Following icons taken from The Noun Project.\nLicensed under the Creative Commons license.\n\ngym equipment by Oliviu Stoian from the Noun Project\nBarbell by Baboon designs from the Noun Project\nCalendar by Ananth from the Noun Project\nSettings by unlimicon from the Noun Project" license:@"Creative Commons"];
            acknowledgementsVC.acknowledgements = [acknowledgementsVC.acknowledgements arrayByAddingObjectsFromArray:@[customLicense]];
            [self.navigationController pushViewController:acknowledgementsVC animated:YES];
        }
    } else if (indexPath.section == 1) {
        DBWCustomizeWorkoutPlanViewController *customizeVC = [[DBWCustomizeWorkoutPlanViewController alloc] init];
        [self.navigationController pushViewController:customizeVC animated:YES];
    }
}

/*
// Override to support conditional editing of the table view.
- (BOOL)tableView:(UITableView *)tableView canEditRowAtIndexPath:(NSIndexPath *)indexPath {
    // Return NO if you do not want the specified item to be editable.
    return YES;
}
*/

/*
// Override to support editing the table view.
- (void)tableView:(UITableView *)tableView commitEditingStyle:(UITableViewCellEditingStyle)editingStyle forRowAtIndexPath:(NSIndexPath *)indexPath {
    if (editingStyle == UITableViewCellEditingStyleDelete) {
        // Delete the row from the data source
        [tableView deleteRowsAtIndexPaths:@[indexPath] withRowAnimation:UITableViewRowAnimationFade];
    } else if (editingStyle == UITableViewCellEditingStyleInsert) {
        // Create a new instance of the appropriate class, insert it into the array, and add a new row to the table view
    }   
}
*/

/*
// Override to support rearranging the table view.
- (void)tableView:(UITableView *)tableView moveRowAtIndexPath:(NSIndexPath *)fromIndexPath toIndexPath:(NSIndexPath *)toIndexPath {
}
*/

/*
// Override to support conditional rearranging of the table view.
- (BOOL)tableView:(UITableView *)tableView canMoveRowAtIndexPath:(NSIndexPath *)indexPath {
    // Return NO if you do not want the item to be re-orderable.
    return YES;
}
*/

/*
#pragma mark - Navigation

// In a storyboard-based application, you will often want to do a little preparation before navigation
- (void)prepareForSegue:(UIStoryboardSegue *)segue sender:(id)sender {
    // Get the new view controller using [segue destinationViewController].
    // Pass the selected object to the new view controller.
}
*/

@end
