//
//  DBWSettingsTableViewController.m
//  Workout
//
//  Created by Ben Rosen on 8/3/17.
//  Copyright © 2017 Ben Rosen. All rights reserved.
//

#import "DBWSettingsTableViewController.h"
#import <VTAcknowledgementsViewController/VTAcknowledgementsViewController.h>
#import <VTAcknowledgementsViewController/VTAcknowledgement.h>
#import "DBWAboutTableViewController.h"
#import "DBWCustomizeWorkoutPlanViewController.h"
#import "DBWAuthenticationManager.h"
#import "AppDelegate.h"

@interface DBWSettingsTableViewController ()

@property (strong, nonatomic) NSIndexPath *selectedIndexPath;

@end

@implementation DBWSettingsTableViewController

- (instancetype)init {
    return [super initWithStyle:UITableViewStyleGrouped];
}

- (void)viewDidLoad {
    [super viewDidLoad];
    
    self.title = @"Settings";
    
    if (UI_USER_INTERFACE_IDIOM() == UIUserInterfaceIdiomPad) {
        [self.splitViewController.viewControllers[1] setViewControllers:@[[[DBWAboutTableViewController alloc] init]]];
        _selectedIndexPath = [NSIndexPath indexPathForRow:0 inSection:0];
    }
    
}

- (void)viewDidAppear:(BOOL)animated {
    [super viewDidAppear:animated];
    [self.tableView selectRowAtIndexPath:_selectedIndexPath animated:NO scrollPosition:UITableViewScrollPositionTop];
}

- (void)didReceiveMemoryWarning {
    [super didReceiveMemoryWarning];
}

#pragma mark - Table view data source

- (NSInteger)numberOfSectionsInTableView:(UITableView *)tableView {
    return 3;
}

- (NSInteger)tableView:(UITableView *)tableView numberOfRowsInSection:(NSInteger)section {
    return section == 0 ? 2 : 1;
}

- (UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath {
    UITableViewCell *cell = [tableView dequeueReusableCellWithIdentifier:@"acknowledgement-identifier"];
    if (!cell) {
        cell = [[UITableViewCell alloc] initWithStyle:UITableViewCellStyleValue1 reuseIdentifier:@"acknowledgement-identifier"];
    }
    
    if (indexPath.section == 0) {
        cell.textLabel.text = indexPath.row == 0 ? @"About" : @"Acknowledgements";
    } else if (indexPath.section == 1) {
        cell.textLabel.text = @"Customize workout plan";
    } else if (indexPath.section == 2) {
        cell.textLabel.text = @"Log out";
    }
    cell.textLabel.textColor = indexPath.section == 2 ? [UIColor redColor] : [UIColor blackColor];
    
    cell.accessoryType = UITableViewCellAccessoryDisclosureIndicator;
    
    
    return cell;
}

- (NSString *)tableView:(UITableView *)tableView titleForHeaderInSection:(NSInteger)section {
    if (section == 0) {
        return @"About";
    } else if (section == 1) {
        return @"Workout";
    } else if (section == 2) {
        return @"Account";
    }
    return @"";
}

- (void)tableView:(UITableView *)tableView didSelectRowAtIndexPath:(NSIndexPath *)indexPath {
    _selectedIndexPath = indexPath;
    
    if (indexPath.section == 0) {
        if (indexPath.row == 0) {
            DBWAboutTableViewController *aboutVC = [[DBWAboutTableViewController alloc] init];
            [self setDetailViewController:aboutVC];
        } else  if (indexPath.row == 1) {
            // automatically the acknowledgements cell
            NSString *path = [[NSBundle mainBundle] pathForResource:@"Acknowledgements" ofType:@"plist"];
            VTAcknowledgementsViewController *acknowledgementsVC = [[VTAcknowledgementsViewController alloc] initWithPath:path];
            acknowledgementsVC.headerText = @"I use the following libraries in this application.";
            acknowledgementsVC.footerText = @"Generated by Cocoapods and icons from The Noun Project";
            
            VTAcknowledgement *customLicense = [[VTAcknowledgement alloc] initWithTitle:@"The Noun Project" text:@"Following icons taken from The Noun Project.\nLicensed under the Creative Commons license.\n\ngym equipment by Oliviu Stoian from the Noun Project\nBarbell by Baboon designs from the Noun Project\nCalendar by Ananth from the Noun Project\nSettings by unlimicon from the Noun Project\nArrow by asianson.design from the Noun Project" license:@"Creative Commons"];
            acknowledgementsVC.acknowledgements = [acknowledgementsVC.acknowledgements arrayByAddingObjectsFromArray:@[customLicense]];
            [self setDetailViewController:acknowledgementsVC];
        }
    } else if (indexPath.section == 1) {
        DBWCustomizeWorkoutPlanViewController *customizeVC = [[DBWCustomizeWorkoutPlanViewController alloc] init];
        [self setDetailViewController:customizeVC];
    } else if (indexPath.section == 2) {
        [DBWAuthenticationManager logOut];
        
        dispatch_async(dispatch_get_main_queue(), ^{
            
            UIImageView __block *transitioningView = [[UIImageView alloc] initWithFrame:self.view.frame];
            transitioningView.backgroundColor = [UIColor colorWithRed:0.201 green:0.220 blue:0.376 alpha:1.00];
            transitioningView.alpha = 0.0;
            [self.view.window addSubview:transitioningView];
            
            [UIView animateWithDuration:0.4 delay:0.0 options:UIViewAnimationOptionCurveEaseIn animations:^{
                transitioningView.alpha = 1.0;
            } completion:^(BOOL finished) {
                AppDelegate *delegate = (AppDelegate *)([UIApplication sharedApplication].delegate);
                self.view.window.rootViewController = delegate.loginVC;
                
                [UIView animateWithDuration:1.0 delay:0.5 options:UIViewAnimationOptionCurveEaseOut animations:^{
                    transitioningView.alpha = 0.0;
                } completion:^(BOOL finished) {
                    [transitioningView removeFromSuperview];
                    
                    for (int i = (int)[self.view.subviews count] - 1; i >= 0; i--) {
                        UIView *subview = self.view.subviews[i];
                        [subview removeFromSuperview];
                    }
                }];
            }];
        });
        
    }
}

// ipad split vc impl vs iphone normal impl
- (void)setDetailViewController:(UIViewController *)viewController {
    if (UI_USER_INTERFACE_IDIOM() == UIUserInterfaceIdiomPad) {
        UINavigationController *detailViewController = UI_USER_INTERFACE_IDIOM() == UIUserInterfaceIdiomPad ? self.splitViewController.viewControllers[1] : self.navigationController;
        detailViewController.viewControllers = @[viewController];
    } else {
        viewController.navigationItem.largeTitleDisplayMode = UINavigationItemLargeTitleDisplayModeNever;
        [self.navigationController pushViewController:viewController animated:YES];
    }
}

@end
